NoiroseServer/api/urls.py
from django.urls import path, include
from rest_framework import routers
from .views import UserListView, UserLoginView, UserRegisterView, SoundLevelViewSet, SoundFileViewSet
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

app_name = 'api'

router = routers.DefaultRouter()
router.register('sound_level', SoundLevelViewSet)
router.register('sound_file', SoundFileViewSet)

urlpatterns = [
    path('user_list/', UserListView.as_view()),             # api/user_list/   로 엔드포인트 설정. 유저 목록 확인 가능.
    path('user_register/', UserRegisterView.as_view(), name='user_register'),     # api/user_register/  회원가입 시 데이터 저장되는 엔드포인트
    path('user_login/', UserLoginView.as_view(), name='user_login'),           # api/user_login/     로그인 시도시, 자격증명 검증하는 엔드포인트
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),          # 사용자 토큰 생성
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),         # 사용자 토큰 리프레시

    path('', include(router.urls))
]



'''
router = routers.DefaultRouter()


router.register('user_list', UserListView.as_view()),
router.register('user_register', UserRegisterView.as_view(), name='user_register'),
router.register('user_login', UserLoginView.as_view(), name='user_login'),

urlpatterns = [
     path('', include(router.urls))
]
'''

NoiroseServer/common/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, include
from . import views
# from api import views


app_name = 'common'  # 이 namespace를 통해 여러 앱 간의 URL 이름 충돌을 방지


urlpatterns = [ 
    path('login/', views.login_request, name='login'),  # 로그인 페이지,        common/login
    path('register/', views.register_request, name='register'),  # 로그인 페이지   common/register
]

# path('register/', auth_views, name='register'),  # 회원가입 페이지

NoiroseServer/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('common/', include('common.urls')),               # common 에서 설정한 urls 앞에 common/ 이 추가됨
    path('main/', include('main.urls')),                   # main 에서 설정한 urls 앞에 main/ 이 추가됨
    path('api/', include('api.urls')),                     # api 에서 설정한 urls 앞에 api/ 이 추가됨
 
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

NoiroseServer/common/models.py
from django.db import models
from django.contrib.auth.models import UserManager, AbstractBaseUser, PermissionsMixin
from django.utils import timezone


class CustomUserManager(UserManager) :
    def create_user(self, userid, password, email, name, apartment, dong, ho):             # 일반 유저 생성. 유저 생성 시 필요한 매개변수 순서 확인할 것!(다른 함수 생성 시 입력순서 중요)
        if not userid :
            raise ValueError("아이디는 필수항목입니다.")
        if not name :
            raise ValueError("이름은 필수항목입니다.")
        if not apartment :
            raise ValueError("아파트명은 필수항목입니다.")
        if not dong :
            raise ValueError("주소(**동)는 필수항목입니다.")
        if not ho :
            raise ValueError("주소(**호)는 필수항목입니다.")

        email = self.normalize_email(email)                                             # 이메일은 이메일 형식으로 변환
        user = self.model(userid=userid, name=name, email=email, apartment=apartment, dong=dong, ho=ho)    # 유저 생성시 입력한 정보를 각각 커스텀 유저의 정보란에 집어넣기 (데이터 입력) 
        user.set_password(password)                                                     # 입력받은 정보를 password 로 설정
        user.is_active = True                                   # 유저 활성화 
        user.save(using=self._db)                               # db에 저장

        return user                                            # 유저 생성
    

    def create_superuser(self, userid, password=None, **extra_fields):             # 슈퍼유저 생성
        extra_fields.setdefault('email', '')
        extra_fields.setdefault('name', '')
        extra_fields.setdefault('apartment', '')                 
        extra_fields.setdefault('dong', 'A')
        extra_fields.setdefault('ho', '')                                # 커스텀유저 모델에서 만든 필드들을 슈퍼유저 생성시에 입력할 수 있게끔 해줌.

        if extra_fields.get('email') == '':
            raise ValueError('이메일은 필수항목입니다.')
        if extra_fields.get('name') == '':
            raise ValueError('이름은 필수항목입니다.')
        if extra_fields.get('apartment') == '':
            raise ValueError('아파트명은 필수항목입니다.')
        if extra_fields.get('dong') not in ('A', 'B', 'C', 'D', 'E'):
            raise ValueError('동은 필수항목이며, 선택지 중 하나를 입력해야 합니다.')
        if extra_fields.get('ho') == '':
            raise ValueError('주소(**호)는 필수항목이며, 0~9999 사이의 값을 입력해야 합니다.')        # 입력받은 값이 없으면 필수로 다시 입력하도록 함
            
        user = self.create_user (userid=userid, password=password, **extra_fields)     # 유저 생성시 입력한 정보를 각각 커스텀 유저의 정보란에 집어넣기 (데이터 입력) 
        user.is_superuser = True
        user.is_staff = True                                  # 슈퍼유저 및 스태프 권한 부여.
        user.save(using=self._db)

        return user

class CustomUser(AbstractBaseUser, PermissionsMixin) :
    userid = models.CharField(max_length = 15, unique=True)
    email = models.EmailField(blank=False, unique=True, default='')
    name = models.CharField(max_length=15)         # 세대주 이름           ## 필수!!! 아파트명, 세대주, 동, 호수
    apartment = models.CharField(max_length = 40, default='아파트명')          # 아파트이름 -> 관리자가 설정
    DONG_CHOICES = (
        ('A', 'A동'),
        ('B', 'B동'),
        ('C', 'C동'),
        ('D', 'D동'),
        ('E', 'E동'),
    )                               
    dong = models.CharField(max_length=20, choices=DONG_CHOICES, default='A')
    ho = models.CharField(blank=False, unique=True, max_length=4, default='0000')             # 커스텀 유저 모델에 사용할 필드들. userid 와 email 은 필수사항.

    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    date_joined = models.DateTimeField(default=timezone.now)
    last_login = models.DateTimeField(blank=True, null=True)

    objects = CustomUserManager()

    USERNAME_FIELD = 'userid'                         # 장고에서 기본적으로 username -> 아이디 로 인식하는 것을 커스텀유저에서 만든 userid 로 바꿔줌
    REQUIRED_FIELDS = ['email', 'name', 'apartment', 'dong', 'ho']

    class Meta :
        ordering = ['-date_joined']
        verbose_name = 'User'
        verbose_name_plural = 'Users'

NoiroseServer/common/views.py
from django.shortcuts import render

# Create your views here.

def login_request(request):
    return render(request, 'common/login.html')


def register_request(request):
    return render(request, 'common/register.html')

NoiroseServer/templates/common/login.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">

  <head>
    <title>DAMOA 로그인</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

    <style>
      .login_box {
        position: absolute;
        left: 50%;
        top: 50%;
        transform: translate(-50%, -50%);
        width: 36%;
        height: 66%;
        box-shadow: 2px 2px 12px 2px black;
        
      }

      .btn {
        border-radius: 1em;
        font-size: 18px;
        width: 400px;
        height: 40px;
      }
    </style>

    <body>
      <div class="login_box">
        <h2 class="start_damoa mt-3" align="center">
          <a href="" style="color: orange">
            DAMOA를 시작해보세요</a>
        </h2><br>

        <div class="container my-3">
          <form method="post" id="login-form" class="post-form" action="{% url 'api:user_login' %}">
            {% csrf_token %}
            {% include "form_errors.html" %}
            <div>
              <h3>로그인 하세요</h3>
              <p>모임에 참여해보세요</p>
            </div>

            <div class="form-group">
              <label for="userid">아이디</label>
              <input type="text" class="form-control" name="userid" id="userid" value="{{ form.userid.value|default_if_none:'' }}">  <!-- value 는 개별 form 필드를 가져와서 커스터마이징 함 -->
              <span style="color: blue;" class="logout_message_required">
                <a href="#">아이디를 잊으셨나요?</a>
              </span>
            </div>

            <div class="form-group">
              <label for="password">비밀번호</label>
              <input type="password" class="form-control" name="password" id="password" value="{{ form.password.value|default_if_none:'' }}">
              <span style="color: blue;">
                <a href="#">비밀번호를 잊으셨나요?</a>
              </span>
            </div><br>

            <div class="form-group" align="center">
              <button type="submit" class="btn btn-primary mb-2">로그인</button>
            </div><br>

            <div align="center">
              damoa가 처음이세요?
              <a href="{% url 'common:register' %}">회원가입</a>
            </div>
          </form>

          
        </div>
      </div>

      <!-- jQuery JS -->
      <script src="{% static 'jquery-3.6.3.min.js' %}"></script>
      <!-- popper -->
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
      <!-- Bootstrap JS -->
      <script src="{% static 'bootstrap.min.js' %}"></script>
    </body>


    
  </html>

  

<script>
  $(document).ready(function() {
      $('#login-form').on('submit', function(e) {
          e.preventDefault(); // Prevent the form from submitting via the browser.
  
          var form = $(this);
          var url = form.attr('action');
  
          $.ajax({
              type: 'POST',
              url: url,
              async: false, // 추가
              contentType: 'application/json; charset=utf-8',
              data: JSON.stringify({
                  userid: $('#userid').val(),
                  password: $('#password').val()
              }),
              dataType: 'json',
              success: function(data) {
                  window.localStorage.setItem('token', data.token);         // Save the token
  
                  alert('로그인에 성공하였습니다.');
                  window.location.href = "/api/user_login";  // redirect to the main page
              },
              error: function (request, status, error) {
                  alert('로그인에 실패하였습니다. 아이디 또는 비밀번호를 확인해주세요.');  
                  window.location.href = "/common/login";  // redirect back to the login page
              }
          });
      });
  
      $.ajaxSetup({
          beforeSend: function(xhr, settings) {
              // if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) // 해당하는 옵션 및 크로스 도메인인 경우에는 '제외'시킴
                  xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
                  const token = window.localStorage.getItem('token');       // Add the token in the Authorization header
                  console.log("Token:", token); // 로그 추가
                  if (token) {
                      xhr.setRequestHeader("Authorization", `Token ${token}`);
                  }
          }
      });
  
  });
  
  function getCookie(name) {
      let cookieValue = null;
      if (document.cookie && document.cookie !== '') {
          const cookies = document.cookie.split(';');
          for (let i = 0; i < cookies.length; i++) {
              const cookie = jQuery.trim(cookies[i]);
              if (cookie.substring(0, name.length + 1) === (name + '=')) {     // Does this cookie string begin with the name we want?
                  cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                  break;
              }
          }
      }
      return cookieValue;
  }
</script>

NoiroseServer/templates/common/register.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">

  <head>
    <title>DAMOA 회원가입</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- main CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <!-- jQuery JS -->
    <script src="{% static 'jquery-3.6.3.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <!-- Bootstrap JS -->
    <script src="{% static 'bootstrap.min.js' %}"></script>

    <style>
      .signup_box {
        position: absolute;
        left: 50%;
        top: 50%;
        transform: translate(-50%, -50%);
        width: 40%;
        height: 90%;
        box-shadow: 2px 2px 12px 2px black;
        overflow: scroll;
      }

      .btn {
        border-radius: 1em;
        font-size: 18px;
        width: 400px;
        height: 40px;
      }
    </style>
  </head>

  <body>
    <div class="signup_box">
      <div class="container my-3">
        <div class="row my-3">
          <div class="col-4">
            <table>
              <tr>
                <td>
                  <a href="">
                    <img alt="damoa logo" src='{% static "img/damoa logo.png" %}' width="80"/></a>
                </td>
                <td>
                  <a href="">
                    <img alt=" damoa" src='{% static "img/damoa.png" %}' width="200"/></a>
                </td>
                <tr></table>

              </div>
              <div class="col-8 text-right">
                <span>또는
                  <a href=" {% url 'common:login' %}">로그인 하세요.</a>
                </span>
              </div>
            </div>

            <form method="post" class="post-form" id="register-form" action="{% url 'api:user_register' %}">
              {% csrf_token %}
              {% include "form_errors.html" %}

              <div class="form-group">
                <label for="userid">아이디</label>
                <input type="text" class="form-control" name="userid" id="userid" value="{{ form.userid.value|default_if_none:'' }}">
              </div>
            
              <div class="form-group">
                <label for="password1">비밀번호</label>
                <input type="password" class="form-control" name="password" id="password" value="{{ form.password.value|default_if_none:'' }}">
              </div>

              <div class="form-group">
                <label for="password2">비밀번호 확인</label>
                <input type="password" class="form-control" name="password2" id="password2" value="{{ form.password2.value|default_if_none:'' }}">
              </div>

              <div class="form-group">
                <label for="email">이메일</label>
                <input type="text" class="form-control" name="email" id="email" value="{{ form.email.value|default_if_none:'' }}">
              </div>

              <div class="form-group">
                <label for="name">성명</label>
                <input type="text" class="form-control" name="name" id="name" value="{{ form.name.value|default_if_none:'' }}">
              </div>

              <div class="form-group">
                <label for="age">나이</label>
                <input type="text" class="form-control" name="age" id="age" value="{{ form.age.value|default_if_none:'' }}">
              </div>

              <div class="form-inline">
                <label for="male">
                  <input type="radio" class="form-control" name="gender" id="male" value="M" checked="checked">남자</label>
                <label for="female">
                  <input type="radio" class="form-control" name="gender" id="female" value="F">여자</label>
              </div><br>

              <div class="form-group">
                <label for="city">거주지</label>
                <select name="city" id="city">
                    <option>::지역 선택::</option>
                    <option value="Seoul">서울</option>
                    <option value="Incheon">인천</option>
                    <option value="Gyeonggi">경기</option>
                    <option value="Gangwon">강원</option>
                    <option value="Chungcheong">충청</option>
                    <option value="Jeolla">전라</option>
                    <option value="Gyeongsang">경상</option>
                </select><br>
                상세주소
                <textarea type="text" class="form-control" name="detail" id="detail"></textarea>
              </div>
              <br>

              <div class="form-group" align="center">
                <button type="submit" class="btn btn-primary mb-2">회원가입</button>
              </div>

            </form>
          </div>
        </div>
      </div>
    </div>

  </body>

</html>

<script>
    $(document).ready(function() {
        $('#register-form').on('submit', function(e) {
            e.preventDefault(); // Prevent the form from submitting via the browser.
    
            var form = $(this);
            var url = form.attr('action');
    
            $.ajax({
                type: 'POST',
                url: url,
                data: form.serialize(),    // 폼 데이터를 직렬화 하여 전송

                success: function(data) {
                    alert('회원가입에 성공하였습니다.');
                    window.location.href = "/common/login";  // redirect to the login page
                },
                error: function(xhr, status, error) {
                    var response = JSON.parse(xhr.responseText);

                    if (response && response.hasOwnProperty('errors')) {
                        var errorMessages = response.errors;
                        var errorMessage = "회원가입에 실패하였습니다. 입력하신 정보를 확인해주세요.";
                        if (errorMessages && errorMessages.length > 0) {
                            errorMessage = errorMessages[0]; // 첫 번째 에러 메시지만 사용
                        }
                        alert(errorMessage);
                    } 
                    else {
                        alert('회원가입에 실패하였습니다. 입력하신 정보를 확인해주세요.');
                    }
                    
                    window.location.href = "/common/register";  // redirect back to the register page
                }

            });
        });
    });
</script>